### ISSUE TITLE
LongNet code

### ISSUE THREAD

**Issue by tomaarsen** [microsoft/unilm#1182]
Hello!

I was reading up on [LongNet](https://arxiv.org/abs/2307.02486) when I wanted to have a glance at the code. It directed me to this repository, which does not seen to have any reference of `LongNet` other than in the README. Can we expect the code for LongNet to be available soon? Or am I perhaps not looking in the right places?

- Tom Aarsen

**Comment by jebarpg** [comment]
not sure yet but just stumbled on this https://github.com/kyegomez/LongNet 
Just starting to look at it now.

**Comment by StrangeTcy** [comment]
> not sure yet but just stumbled on this [kyegomez/LongNet](https://github.com/kyegomez/LongNet) Just starting to look at it now.

Great attempt, but it claims to be a simplified version.
Then again, a collective effort might lead to a complete implementation

**Comment by chaseaucoin** [comment]
> i'm going to guess and say they aren't going to share it any time soon

it says right in the paper "Code is available at https://aka.ms/LongNet." which leads here. They wouldn't lie in a published paper would they?

**Comment by donglixp** [comment]
The module will be merged into the torchscale package for easier usage.

https://github.com/microsoft/torchscale

**Comment by FrancescoSaverioZuppichini** [comment]
> https://github.com/kyegomez/LongNet

man is microsoft

**Comment by FrancescoSaverioZuppichini** [comment]
> > not sure yet but just stumbled on this [kyegomez/LongNet](https://github.com/kyegomez/LongNet) Just starting to look at it now.
> 
> Great attempt, but it claims to be a simplified version. Then again, a collective effort might lead to a complete implementation

It's microsoft at the end of the day

**Comment by FrancescoSaverioZuppichini** [comment]
> > not sure yet but just stumbled on this [kyegomez/LongNet](https://github.com/kyegomez/LongNet) Just starting to look at it now.
> 
> Great attempt, but it claims to be a simplified version. Then again, a collective effort might lead to a complete implementation

the forward pass in the Attention function

```
    def forward(self, x):
        batch_size, seq_len, _ = x.shape

        # Split and sparsify
        x = x.view(batch_size, -1, self.segment_size, self.d_model)
        x = x[:, :, :: self.dilation_rate, :]

        # Perform attention
        attn_output, _ = self.attention(x, x, x)

        #apply dropout
        attn_output = self.dropout(attn_output)

        # Scatter and concatenate 
        attn_output = attn_output.view(batch_size, -1, self.d_model)
        return attn_output
```

looks gpt-4 generated with human intervention - look at the commends, most of them starts with # <CAPITAL_CASE> which is GPT-4 while some of them are #<LOWER_CASE> probably human - nothing against it, just food for thoughts

**Comment by tomaarsen** [comment]
Well spotted. I'll be waiting for a true drop-in replacement so I can do some benchmarking.

**Comment by JacksonZ03** [comment]
> not sure yet but just stumbled on this https://github.com/kyegomez/LongNet Just starting to look at it now.

There's a lot of controversy around this contributor. There has been rumours that his code is generated by ChatGPT and doesn't actually run. https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/pics/fake.png

**Comment by kyegomez** [comment]
> > > not sure yet but just stumbled on this [kyegomez/LongNet](https://github.com/kyegomez/LongNet) Just starting to look at it now.
> > 
> > 
> > Great attempt, but it claims to be a simplified version. Then again, a collective effort might lead to a complete implementation
> 
> the forward pass in the Attention function
> 
> ```
>     def forward(self, x):
>         batch_size, seq_len, _ = x.shape
> 
>         # Split and sparsify
>         x = x.view(batch_size, -1, self.segment_size, self.d_model)
>         x = x[:, :, :: self.dilation_rate, :]
> 
>         # Perform attention
>         attn_output, _ = self.attention(x, x, x)
> 
>         #apply dropout
>         attn_output = self.dropout(attn_output)
> 
>         # Scatter and concatenate 
>         attn_output = attn_output.view(batch_size, -1, self.d_model)
>         return attn_output
> ```
> 
> looks gpt-4 generated with human intervention - look at the commends, most of them starts with # <CAPITAL_CASE> which is GPT-4 while some of them are #<LOWER_CASE> probably human - nothing against it, just food for thoughts

50% of all the code generated on GitHub is AI generated but does the code actually complete it's intended purpose? I think you're focused on things that do not matter in the grand scheme of things.

**Comment by kyegomez** [comment]
> > not sure yet but just stumbled on this https://github.com/kyegomez/LongNet Just starting to look at it now.
> 
> There's a lot of controversy around this contributor. There has been rumours that his code is generated by ChatGPT and doesn't actually run. https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/pics/fake.png

If I told you I am God, would you believe me without any proof? 

And, that person provides no definitive evidence for their claim, they also seem to envious interesting.

And, does your code run the first time you make it? 

There's a 80% chance it doesn't, that's why I open source things so people can make it work.

If my code doesn't work I encourage you to submit a pull request and help make it more reliable and satisfy your thirst

**Comment by FrancescoSaverioZuppichini** [comment]
> > > > not sure yet but just stumbled on this [kyegomez/LongNet](https://github.com/kyegomez/LongNet) Just starting to look at it now.
> > > 
> > > 
> > > Great attempt, but it claims to be a simplified version. Then again, a collective effort might lead to a complete implementation
> > 
> > 
> > the forward pass in the Attention function
> > ```
> >     def forward(self, x):
> >         batch_size, seq_len, _ = x.shape
> > 
> >         # Split and sparsify
> >         x = x.view(batch_size, -1, self.segment_size, self.d_model)
> >         x = x[:, :, :: self.dilation_rate, :]
> > 
> >         # Perform attention
> >         attn_output, _ = self.attention(x, x, x)
> > 
> >         #apply dropout
> >         attn_output = self.dropout(attn_output)
> > 
> >         # Scatter and concatenate 
> >         attn_output = attn_output.view(batch_size, -1, self.d_model)
> >         return attn_output
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > looks gpt-4 generated with human intervention - look at the commends, most of them starts with # <CAPITAL_CASE> which is GPT-4 while some of them are #<LOWER_CASE> probably human - nothing against it, just food for thoughts
> 
> 50% of all the code generated on GitHub is AI generated but does the code actually complete it's intended purpose? I think you're focused on things that do not matter in the grand scheme of things.

yes I agree, I wasn't say "hey it's generated thus it's wrong/bad", I was just commenting out of curiosity and I am no truth machine so I cannot know - to me there is not issue, I'd just love to have the original implementation. The original implementation should be on top of I don't remember the name a sparse attention transformer but for that implementation, it doesn't seem to be the case but consider I am hangover now

**Comment by JacksonZ03** [comment]
> > > not sure yet but just stumbled on this https://github.com/kyegomez/LongNet Just starting to look at it now.
> > 
> > 
> > There's a lot of controversy around this contributor. There has been rumours that his code is generated by ChatGPT and doesn't actually run. https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/pics/fake.png
> 
> If I told you I am God, would you believe me without any proof?
> 
> And, that person provides no definitive evidence for their claim, they also seem to envious interesting.
> 
> And, does your code run the first time you make it?
> 
> There's a 80% chance it doesn't, that's why I open source things so people can make it work.
> 
> If my code doesn't work I encourage you to submit a pull request and help make it more reliable and satisfy your thirst

If there is 80% chance it won't run, then let that be known. Nobody wants to waste time fixing bad code. I'm not saying AI generated code is bad, but test it before releasing it and be transparent. It's very pretentious and deceiving to declare that you have made an implementation of the code, when it doesn't even work. The same goes for the Tree of Thoughts repo as well. You closed a issue and deliberately ignored the original authors of the paper when they requested that you provide a link to their actual implementation because yours couldn't reproduce the results in the paper - https://github.com/kyegomez/tree-of-thoughts/issues/54, https://github.com/kyegomez/tree-of-thoughts/issues/55, https://github.com/kyegomez/tree-of-thoughts/issues/56

**Comment by JacksonZ03** [comment]
![image](https://github.com/microsoft/unilm/assets/60581068/f6f5e669-6f21-4766-b2aa-3719c0b24c78)

Also, please explain how a 19-year-old who posts broken, AI-generated code is capable of running an AI research organisation of 1,500+ researchers? 🤦🏼‍♂️

**Comment by kyegomez** [comment]
> > > > not sure yet but just stumbled on this https://github.com/kyegomez/LongNet Just starting to look at it now.
> 
> > > 
> 
> > > 
> 
> > > There's a lot of controversy around this contributor. There has been rumours that his code is generated by ChatGPT and doesn't actually run. https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/pics/fake.png
> 
> > 
> 
> > If I told you I am God, would you believe me without any proof?
> 
> > 
> 
> > And, that person provides no definitive evidence for their claim, they also seem to envious interesting.
> 
> > 
> 
> > And, does your code run the first time you make it?
> 
> > 
> 
> > There's a 80% chance it doesn't, that's why I open source things so people can make it work.
> 
> > 
> 
> > If my code doesn't work I encourage you to submit a pull request and help make it more reliable and satisfy your thirst
> 
> 
> 
> If there is 80% chance it won't run, then let that be known. Nobody wants to waste time fixing bad code. I'm not saying AI generated code is bad, but test it before releasing it and be transparent. It's very pretentious and deceiving to declare that you have made an implementation of the code, when it doesn't even work. The same goes for the Tree of Thoughts repo as well. You closed a issue and deliberately ignored the original authors of the paper when they requested that you provide a link to their actual implementation because yours couldn't reproduce the results in the paper - https://github.com/kyegomez/tree-of-thoughts/issues/54, https://github.com/kyegomez/tree-of-thoughts/issues/55, https://github.com/kyegomez/tree-of-thoughts/issues/56 

Revisiting this please excuse my response and tone, I don't sleep for 2-3 days at a time and I often forget how to interact with people since I write more code than I speak language.

Ai did not generate this, ai did generate the specs that helped me simplify the paper.

In the beginning, the probability of it being functional in respect to the papers original implementation was around 20% after countless iterations that has been increased to around 45-60% depending on who you ask.

And I try to rigorously test every push, I have tested LongNet many times all ready but I often lack the compute to test for billion long sequences.

And they did not request me to reference their repo they outright commanded me. I would've referenced it had they not commanded me.

**Comment by kyegomez** [comment]
> ![image](https://github.com/microsoft/unilm/assets/60581068/f6f5e669-6f21-4766-b2aa-3719c0b24c78)
> 
> 
> 
> Also, please explain how a 19-year-old who posts broken, AI-generated code is capable of running an AI research organisation of 1,500+ researchers? 🤦🏼‍♂️

What code is broken? Please let me know.

**Comment by zh-plus** [comment]
> not sure yet but just stumbled on this https://github.com/kyegomez/LongNet Just starting to look at it now.

FYI: 
> Note: please unstar https://github.com/kyegomez/tree-of-thoughts which CANNOT replicate paper results.
In fact, people have reported that his code https://github.com/kyegomez/tree-of-thoughts/issues/52 https://github.com/kyegomez/tree-of-thoughts/issues/41 https://github.com/kyegomez/tree-of-thoughts/issues/60, and is [probably automatically generated by ChatGPT](https://github.com/princeton-nlp/tree-of-thought-llm/blob/master/pics/fake.png), and [kyegomez has done so for other popular ML methods](https://twitter.com/qbitium/status/1663954096741814272), while intentionally refusing to link to official implementations for his own interests (see https://github.com/kyegomez/tree-of-thoughts/issues/54, https://github.com/kyegomez/tree-of-thoughts/issues/55, https://github.com/kyegomez/tree-of-thoughts/issues/56). Unfortunately, Google/Github searches go to kyegomez's malicious repo by default as it has more stars. Please UNSTAR his repo and STAR this to help other people avoid being misled, thanks!

from https://github.com/princeton-nlp/tree-of-thought-llm#official-repo-of-tree-of-thoughts-tot

I believe this repo should not be promoted.

**Comment by JacksonZ03** [comment]
> 

My point was about the broken code. Everybody makes mistakes and no code is perfect. My point is about how you need to be more wary about the stuff you put in your readme and be a lot more transparent and a lot less deceptive and pretentious. The readme is the first thing that people see when they click on your repo so don't omit things or even worse, write statements that are straight-up lies (like the fact that you run an AI research organisation that has over 1500+ researchers when you obviously don't).
Because AI is such a popular domain, many beginners will be interested in this kind of stuff and the last thing I'd want is for people to be misled. The best part about the open-source community is the support we have for each other no matter what level you are at, but the only way to get recognised is to put out good, useful contributions. Lying and being deceptive may work in the short term for a quick "win" but it's only a matter of time before you get found out. And when that happens, that's when you lose your reputation and other people's trust.

**Comment by FrancescoSaverioZuppichini** [comment]
> > > ![image](https://user-images.githubusercontent.com/60581068/252164223-f6f5e669-6f21-4766-b2aa-3719c0b24c78.png)
> > > Also, please explain how a 19-year-old who posts broken, AI-generated code is capable of running an AI research organisation of 1,500+ researchers? 🤦🏼‍♂️
> > 
> > 
> > What code is broken? Please let me know.
> 
> My point was about the broken code. Everybody makes mistakes and no code is perfect. My point is about how you need to be more wary about the stuff you put in your readme and be a lot more transparent and a lot less deceptive and pretentious. The readme is the first thing that people see when they click on your repo so don't omit things or even worse, write statements that are straight-up lies (like the fact that you run an AI research organisation that has over 1500+ researchers when you obviously don't). Because AI is such a popular domain, many beginners will be interested in this kind of stuff and the last thing I'd want is for people to be misled. The best part about the open-source community is the support we have for each other no matter what level you are at, but the only way to get recognised is to put out good, useful contributions. Lying and being deceptive may work in the short term for a quick "win" but it's only a matter of time before you get found out. And when that happens, that's when you lose your reputation and other people's trust.

+ the implementation doesn't use anything sparse to my understanding

**Comment by evolu8** [comment]
@kyegomez 
I watched the debacle unfold on Tree of Thoughts. Now I'm watching this. I think you want to do the right thing. But, to be fair, you are not hearing people. People with a lot of experience. No one likes being told what is what. No one does. Even less so when we are young. Here's my take, in case it is useful:

- No one wants generated code put on Github, because it is something we can all do very quickly and easily. We just don't want code that is 80% likely not to work. It's not really code. It's pseudo code. Which is a big reason for you getting a lot of pushback. Some day it may even get banded due to the risk of degradation (see: https://arxiv.org/abs/2305.17493)
- I say this because I hope you can hear the constructive message in it: Your tone has come across as combative and belligerent. Whether that is your intent or not, that is how it comes across. This is pretty much the opposite of the tone required to build a following and community (if that is your goal). For a following, you first need to listen to what people want and accept it, before you can shape it.
- The impression from your readme pages is one of 'over-sell'. It does not come across as real. And on digging a little, it appears even less so. If you focus on first impressions this hard, the second impression people will always have is a disappointment. 

All of these things are fixable. No, I'm not telling you that you must fix them. But I am advising you that it will help you in your journey. For context, I sold my first company before you were born (literally). And I'm now a senior director in an AI group within a very large company. That doesn't mean I'm right. But it does mean I've seen a lot. 

Like I say, I hope this helps. Enjoy our brave new world.

**Comment by jploski** [comment]
Publishing a paper with a prominent link to code in abstract and then  not releasing the code is just sleazy.

**Comment by alexisrozhkov** [comment]
I've also been disappointed by the lack of promised official implementation, so I'm currently working on a [re-implementation of dilated self-attention](https://github.com/alexisrozhkov/dilated-self-attention) just for fun.

Although many crucial parts are missing at the moment (such as distributed training support, handling batches of sequences with different lengths, using optimised self-attention implementation, etc), the scaling of inference time and GPU RAM usage seem to be linear as expected (benchmarking code and results are included), so it should be possible to use it in some capacity already.

I hope that it might be useful as a starting point for someone, PRs are also welcome!

**Comment by lkurlandski** [comment]
> 

It's not published, merely on ArXiV :).

**Comment by FrancescoSaverioZuppichini** [comment]
> > 
> 
> It's not published, merely on ArXiV :).

so yeah hard F - crazy that people lie in a research paper

**Comment by lkurlandski** [comment]
> > It's not published, merely on ArXiV :).
> 
> so yeah hard F - crazy that people lie in a research paper

Usually they would write “the code will be available at {link}”. This seems to be a typo. Once they publish the paper, I’m sure the code will be available at that destination. Its not really a lie, more likely an extremely minor error. They don’t want anyone using their code and stealing their idea before the paper gets published and the credit is properly attributed. Also, the entire point of putting a paper on ArXiV before publication like this is to get feedback and reactions from the rest of the research community. The paper is not supposed to be taken seriously until after it has gone through peer review.

**Comment by FrancescoSaverioZuppichini** [comment]
> > > It's not published, merely on ArXiV :).
> > 
> > 
> > so yeah hard F - crazy that people lie in a research paper
> 
> Usually they would write “the code will be available at {link}”. This seems to be a typo. Once they publish the paper, I’m sure the code will be available at that destination. Its not really a lie, more likely an extremely minor error. They don’t want anyone using their code and stealing their idea before the paper gets published and the credit is properly attributed. Also, the entire point of putting a paper on ArXiV before publication like this is to get feedback and reactions from the rest of the research community. The paper is not supposed to be taken seriously until after it has gone through peer review.

Okay makes sense, still if I see a link to the code I'd expect to be there but what you are saying makes sense - thanks a lot

**Comment by lkurlandski** [comment]
> > > > It's not published, merely on ArXiV :).
> > > 
> > > 
> > > so yeah hard F - crazy that people lie in a research paper
> > 
> > 
> > Usually they would write “the code will be available at {link}”. This seems to be a typo. Once they publish the paper, I’m sure the code will be available at that destination. Its not really a lie, more likely an extremely minor error. They don’t want anyone using their code and stealing their idea before the paper gets published and the credit is properly attributed. Also, the entire point of putting a paper on ArXiV before publication like this is to get feedback and reactions from the rest of the research community. The paper is not supposed to be taken seriously until after it has gone through peer review.
> 
> Okay makes sense, still if I see a link to the code I'd expect to be there but what you are saying makes sense - thanks a lot

Yes, I am irritated as well…the Recurrent Memory Transformer paper they claim to outperform has their source code available. It functions very differently from LongNet, but could be worth checking out. 

On a completely different note, I found the LongNet paper rather misleading and poorly executed. They compared their novel architecture to a similar arch from four years ago. They also barely met the minimal bar for testing LongNet on long sequences. Also, their 1B token claim is rather bullshit because apparently you need an ENTIRE GPU to actually process that length. As is, this paper is unlikely to make it through peer review in a top tier conference, so it might be a long time before we get their code.

**Comment by jploski** [comment]
> > > > > It's not published, merely on ArXiV :).
> > > > 
> > > > 
> > > > so yeah hard F - crazy that people lie in a research paper
> > > 
> > > 
> > > Usually they would write “the code will be available at {link}”. This seems to be a typo. Once they publish the paper, I’m sure the code will be available at that destination. Its not really a lie, more likely an extremely minor error. They don’t want anyone using their code and stealing their idea before the paper gets published and the credit is properly attributed. Also, the entire point of putting a paper on ArXiV before publication like this is to get feedback and reactions from the rest of the research community. The paper is not supposed to be taken seriously until after it has gone through peer review.
> > 
> > 
> > Okay makes sense, still if I see a link to the code I'd expect to be there but what you are saying makes sense - thanks a lot
> 
> Yes, I am irritated as well…the Recurrent Memory Transformer paper they claim to outperform has their source code available. It functions very differently from LongNet, but could be worth checking out.

Also in a similar vein check out RetNet - with source code both from authors and another independent implementatin, and also a very realistic contribution (unlike the "1B token attention" claim) by replacing O(n) time complexity attention by O(1) retention... which being an RNN theoretically has "infinite" token span. But practical capacity of course will depend on how much information you can accumulate into a given amount of (GPU) memory.

**Comment by FrancescoSaverioZuppichini** [comment]
thanks a lot, will check

**Comment by lkurlandski** [comment]
> 

Haha, yes I find it rather amusing that we worked so hard to get away from RNNs and eventually arrived at the Transformer. Now, new architectures keep popping up that seem to be leaning back towards recurrence.

**Comment by jploski** [comment]
> Haha, yes I find it rather amusing that we worked so hard to get away from RNNs and eventually arrived at the Transformer. Now, new architectures keep popping up that seem to be leaning back towards recurrence.

The reason why we worked to get away from RNNs is because we lacked insight into how to train them efficiently and how to avoid numerical instability when stacking many layers. The RetNet paper elegantly fixes the first problem (while previously known regularization techniques fix the second). Time will hopefully show how well the technique scales and whether the capacity of RNN layers (instead of KV caches) to store information is a problem. I'm only worried that with everyone committed to "tried and true" attention-based transformers, no serious try will be given to retention-based architectures (indeed I've already seen insinuations elsewhere that "RetNet only works until 7B"... without any actual proof). There's certainly a lot danger of sunk cost fallacies here.

**Comment by lkurlandski** [comment]
> > Haha, yes I find it rather amusing that we worked so hard to get away from RNNs and eventually arrived at the Transformer. Now, new architectures keep popping up that seem to be leaning back towards recurrence.
> 
> The reason why we worked to get away from RNNs is because we lacked insight into how to train them efficiently and how to avoid numerical instability when stacking many layers. The RetNet paper elegantly fixes the first problem (while previously known regularization techniques fix the second). Time will hopefully show how well the technique scales and whether the capacity of RNN layers (instead of KV caches) to store information is a problem. I'm only worried that with everyone committed to "tried and true" attention-based transformers, no serious try will be given to retention-based architectures (indeed I've already seen insinuations elsewhere that "RetNet only works until 7B"... without any actual proof). There's certainly a lot danger of sunk cost fallacies here.



> > Haha, yes I find it rather amusing that we worked so hard to get away from RNNs and eventually arrived at the Transformer. Now, new architectures keep popping up that seem to be leaning back towards recurrence.
> 
> The reason why we worked to get away from RNNs is because we lacked insight into how to train them efficiently and how to avoid numerical instability when stacking many layers. The RetNet paper elegantly fixes the first problem (while previously known regularization techniques fix the second). Time will hopefully show how well the technique scales and whether the capacity of RNN layers (instead of KV caches) to store information is a problem. I'm only worried that with everyone committed to "tried and true" attention-based transformers, no serious try will be given to retention-based architectures (indeed I've already seen insinuations elsewhere that "RetNet only works until 7B"... without any actual proof). There's certainly a lot danger of sunk cost fallacies here.

Checkout the new “Backpack Language Models”. Won best paper at ACL this summer. Havn’t had the time to read it end-to-end, but it seems like another promising avenue.

**Comment by donglixp** [comment]
Please refer to the https://github.com/microsoft/torchscale repo for architecture stuff.

**Comment by endomorphosis** [comment]
![image](https://github.com/microsoft/unilm/assets/3405202/daca4169-28d3-4dbe-8a3e-bf4ee931b4d5)
