### ISSUE TITLE
can you updates kosmos-2 the code of preparing dataset

### ISSUE THREAD

**Issue by hujunchao** [microsoft/unilm#1222]
Thank you for your great work. I can't wait to train it. But I don't kown how to preparing dataset, can you show me the code?
Thank!

**Comment by pengzhiliang** [comment]
Hi, @hujunchao . I hope I can finish it in these two days.

**Comment by hujunchao** [comment]
where can us find the code of preparing dataset?

**Comment by JierunChen** [comment]
Same request for releasing the code of preparing the dataset.

**Comment by pengzhiliang** [comment]
Hi, @hujunchao @JierunChen sorry for the late response. I'm sure I will implement it in these two days.

**Comment by JierunChen** [comment]
@pengzhiliang Hi, thanks for your efforts and help. But I got one more question on the update. After I download the GRIT dataset from [huggingface](https://huggingface.co/datasets/zzliang/GRIT), I got some parquet files instead of the tar files. Could you advise more on how to convert the parquet files to images and JSON files? Appreciate your help.

**Comment by JierunChen** [comment]
@pengzhiliang Thanks for your update. I follow the instructions to download the grit dataset from huggingface. But there are some failure cases, as shown in the output "failed to download: 0.081 - failed to resize: 0.004". Is it normal? How should we deal with that?

**Comment by pengzhiliang** [comment]
This might be due to some URLs corresponding to images that no longer exist. I don't think it has a significant impact; it just reduces the number of images slightly.

**Comment by JierunChen** [comment]
@pengzhiliang Thanks for your instant response and looking forward to your further code update : ）
