### ISSUE TITLE
BEiTv2  Codebook Visualization

### ISSUE THREAD

**Issue by Zhcyoung** [microsoft/unilm#1380]
How can I visualize the codebook like the image below, and is the code related to this part open source?
![dog](https://github.com/microsoft/unilm/assets/54757411/a7080a04-d974-4580-8005-7e8156ea96ab)

**Comment by pengzhiliang** [comment]
Hi,  @Zhcyoung. Thanks for the interest! 
I apologize for not being able to find the visualization code you need since it has been a long time. However, the idea is very simple: for each code in the codebook, iterate through the entire eval set and draw the corresponding locations on the images.  The pseudocode is following:

```python
for code in codebook:
    for image in eval_dataset:
        tokens = vqkd(image)
        if code in tokens:
            locations = find_patch_index_based_on_code(code)
            visualize(image, locations)
```

**Comment by Zhcyoung** [comment]
ok , Thanks for your response
