### ISSUE TITLE
In SROIE dataset: how to assign the label to each word/token?

### ISSUE THREAD

**Issue by persistforever** [microsoft/unilm#151]
Hi, I have a question about how to assign the label to each word or token in SROIE dataset.

For example, there is a page that has the label dict as follow,
{'company': 'XXX', 'address': 'AAA, BBB, CCC', 'data': '2016/05/05', 'total': '12.90'}

the SROIE official dataset only provide the text-level OCR results. However, they do not provide the token-level or word-level OCR results. 

For example, there is a OCR result provided by SROIE official dataset that 'date: 2016/05/05 11:30pm'. Since the label of 'DATE' is '2016/05/05'. How can I split the '2016/05/05' from 'date: 2016/05/05 11:30pm'. They only give the coordinates of 'date: 2016/05/05 11:30pm'. How can I get the coordinates of '2016/05/05'?

Another question. If there are many texts '12.90' in the page, which one should I label the 'TOTAL' tag? Do you use human-labeling?

Thanks!

**Comment by YifeiYang210** [comment]
I think it needs pre-process and post-process. 

Pre-process.
I think the token-level labels are extraced according to the offical given entity-level labels. But matching the part of the given labels and also need some dirty work to clean the dataset, which protect the whole date not be cut manually.

Post-process.
For example, date:[2016/05/05 11:30pm] as the final model output, should be cut using the Regular Expression. But train the model should still insist on the raw data such as [2016/05/05 11:30pm]

**Comment by YifeiYang210** [comment]
@wolfshow  @ranpox

I contact with the SROIE offical about the dataset. Their aim is an entity-level end-to-end model rather than the token-level end-to-end model.

So I'm curious about what input format is your model for the SROIE task, choice A or choice B?
=======================
choice A. 
BOOK TA .K (TAMAN DAYA) SDN BHD	S-COMPANY
=======================
choice B. 
BOOK 	S-COMPANY
TA .K        S-COMPANY
(TAMAN DAYA)        S-COMPANY
SDN       S-COMPANY
BHD       S-COMPANY
=======================
As for the paper mentioned, it seems like the choice B. But how to solve the 2D box coordinates , each token location is different. And e only have the box coordinates not the token coordinates. 

So I guess, you share the box coordinates to all the token coordinates belonging to the box.
Am I right?

**Comment by wolfshow** [comment]
@persistforever and @YifeiYang210, we pre-processed the dataset into token-level labels, which means your option B.

**Comment by YifeiYang210** [comment]
Thank you. 
The question feels a little foolish because I think the 2D box coordinates do not match the coodinates of each token. Sometimes the token in the box may be in the same line, but not always the same column. So I will try another work to specify it.
