### ISSUE TITLE
Could you please release the dev results?

### ISSUE THREAD

**Issue by memeda** [microsoft/unilm#28]
It's very nice to get the `test` result, but in fact it is useless for researching because we should't touch the test.

So if it is convenient, please release the `dev` result.  I know it is critical because providing a useful guild is already very very very nice, but I make this request because of the high-quality of the repo and maintainer. 

Thanks a lot.

**Comment by donglixp** [comment]
Hi @memeda ,

Thanks for your interest in our work! The dev data are also included in the data folder. You could easily switch test.src to dev.src, so that you could obtain the prediction results of the input examples. We provide test predictions in case you would like to compare our model using other evaluation metrics or conduct the human evaluation.

**Comment by memeda** [comment]
😂  I'm request the dev predictions, not the src...
I'm really running the code to generate the cnndm dev result. But it is not easy. No docker, no enough gpu.
