### ISSUE TITLE
data is training for only first 512 words of document

### ISSUE THREAD

**Issue by lalitr994** [microsoft/unilm#430]
dataset (images/ocr) for which I am training layoutlmv2 token classification model consist words more than 512. but somehow only 512 words are only feeding to the model. so, other words are not training. any way by which I can train the whole document.

**Comment by wolfshow** [comment]
@lalitr994 people usually split the document into multiple samples, where each of them is 512 or less.

**Comment by huschi** [comment]
@wolfshow do they also split the image into several parts? Or only the tokens and use the original image?

**Comment by lalitr994** [comment]
> @wolfshow do they also split the image into several parts? Or only the tokens and use the original image?

I did the same. only split the tokens and process into batches with the same image.

**Comment by huschi** [comment]
@wolfshow, @lalitr994

Let's assume we fine-tune a model.
10 documents and each document has 1024 tokens.

To fine-tune the model I could split the 1024 tokens into two lists with 512 tokens.
For each list, I assign the same image (no need to crop the image into two parts) and at the end, we have a dataset with 20 examples instead of 10?
