### ISSUE TITLE
Text extraction from raw image 

### ISSUE THREAD

**Issue by rajsaraiya009** [microsoft/unilm#503]
Hello, I was able to run your pic_inference.py file. Now my question is I have observed that the pretrained models work on line-by-line text extraction. When I tried to upload the document full of text it catches only one word from the particular document. Was curious to know how we can extract all the text from the particular page.

**Comment by NielsRogge** [comment]
Hi,

TrOCR is a text recognition model, not a text detection model. You still need a separate text detection model to get all single-line texts from a PDF. You can use for example take a look at this library for textline detection: https://github.com/qurator-spk/eynollah

**Comment by rajsaraiya009** [comment]
So is there any way to connect the output of the above link with the Trocr model and read text?

**Comment by NielsRogge** [comment]
Yes, as stated on that page, you can run the command-line program and its output will be in XML. This contains the bounding boxes of the textlines appearing in the image. This can be used as input for the TrOCR model.

**Comment by jhonlinemail** [comment]
Greetings @NielsRogge! You asked to use the @Huggingface forum instead of this issues section, so I posted a follow-up question to this post on the beginner discussion forum: 

https://discuss.huggingface.co/t/how-to-do-full-page-analysis-with-trocr-integrating-with-text-segmentation-analysis/39416

Thank you for your assistance, examples and explanation. Please bear with me as I am a novice.
