### ISSUE TITLE
[BEIT] Pre-trained models based on ImageNet-1k instead of ImageNet-20k

### ISSUE THREAD

**Issue by zhaoshaojun** [microsoft/unilm#527]
The BEIT models are great. The pre-trained models and fine-tuned models are all based on the ImageNet-20k data, which makes sense and great. But could you guys also release the pre-trained models based on ImageNet-1k? That could be very helpful for benchmark and comparisons.

Thanks and looking forward to your responses.

**Comment by donglixp** [comment]
@addf400 can share the checkpoints.

**Comment by donglixp** [comment]
@zhaoshaojun   It has been added to our release plan and will be available soon (together with other checkpoints).

**Comment by black0017** [comment]
Any chance that the BEiT v2 ViT-Large pretrained on ImageNet-21K (aka 22K) will be shared? @donglixp 

As far as I remember, they were available this summer and disappeared for some reason.

**Comment by pengzhiliang** [comment]
Hi, @black0017 
After multiple verifications, the provided link is valid. You can use wget:
```bash
wget "https://conversationhub.blob.core.windows.net/beit-share-public/beitv2/beitv2_large_patch16_224_pt1k_ft21k.pth?sv=2021-10-04&st=2023-06-08T11%3A16%3A02Z&se=2033-06-09T11%3A16%3A00Z&sr=c&sp=r&sig=N4pfCVmSeq4L4tS8QbrFVsX6f6q844eft8xSuXdxU48%3D"
```
or download directly with your browser after checking your network connection again.

**Comment by black0017** [comment]
Oh sorry @pengzhiliang  , I misunderstood. 

I thought the BeiTv2 was pretrained on ImageNet21k and then fine-tuned on imagenet1K, but it seems to be the opposite. `beitv2_large_patch16_224_pt1k_ft21k` -->  likely means pre-trained on imagenet 1k.

I got confused because for BeiT (v1) there are ImageNet21k (self-supervised) pretrained checkpoints and I would be very interested to see the performance of BeiTv2 with pure imagenet21K pretraining. 

Not so many self-supervised model weights are out there with ImageNet21K pretraining.

Thanks a lot and have a nice day,

Nikolas
