### ISSUE TITLE
LayoutReader, missing words in the output sequence

### ISSUE THREAD

**Issue by HoomanKhosravi** [microsoft/unilm#582]
Model I am using LayoutReader:

When I use layoutReader, almost always, some part of the input sequence is missing from the output. I visualized an example here:

![out1](https://user-images.githubusercontent.com/32684826/147993647-885e7ab3-33fa-488a-b2c7-aaca829cc498.jpg)

The red words were included in the input sequence but were not part of the output. The program still computes a BLEU score and finishes without errors. Is this behaviour normal? why does this happen?

Thanks.

**Comment by HYPJUDY** [comment]
Thanks for your question and visualization!
There might be two reasons for the missing words:
1) The maximum sequence length (e.g., 512) is smaller than the document length.
2) As mentioned in https://github.com/microsoft/unilm/issues/583, LayoutReader might generate repeated words. When there are some repeating words, there should be missing words. 

In addition to re-training the model, some post-processing methods might be helpful for this issue. If the document is very long, you could try splitting it into several parts and process each part with LayoutReader at a time. Otherwise, you could remove duplicated predictions and insert the missed indices according to OCR predictions in post-processing.
