### ISSUE TITLE
LayoutReader: repeated words in the output sequence

### ISSUE THREAD

**Issue by HoomanKhosravi** [microsoft/unilm#583]
Model I am using (LayoutReader)

The layoutReader output, sometimes repeats the same words several times in the output sequence. In other words, when following the  predicted reading order, after passing a particular word you will come back to it again.

I had to modify decode_seq2seq.py so that It will only consider the first appearance of each words. Is this an expected behaviour from the layoutReader? why does this happen?

Hooman

**Comment by HYPJUDY** [comment]
It is expected behavior for the LayoutReader. Since LayoutReader turns the reading order prediction problem into a **generic sequence generation problem**, it might generate repeated words (and some words might miss). When the training data is large enough, this behavior might be insignificant.
Removing duplicated predictions should have an advantage to the **specific sequence re-ordering task**. In addition to your method, the following methods might also be helpful to remove duplications: 1) set the probabilities of previously generated indices to zero during decoding, 2) remove duplicated predictions and insert the missed indices according to OCR predictions in postprocessing.

**Comment by HoomanKhosravi** [comment]
Thank you, that makes sense.
