### ISSUE TITLE
TrOCR pretrained model 

### ISSUE THREAD

**Issue by BroadJJ** [microsoft/unilm#658]
Thanks for sharing models.

I'm a little confused.
Is the "trocr-base-printed.pt" model already fine-tuned on sroie dataset?
or is that the stage 2 model?

**Comment by wolfshow** [comment]
@BroadJJ fine-tuned on sroie.

**Comment by cramraj8** [comment]
@wolfshow  Since there are 2 stages of pre-training, is **trocr-base-stage1** is pre-trained model after pre-training-stage-1 or pre-training-stage-2 ?

One more question: for second stage of pre-training, did you combine all 3 different sources of dataset to train or pre-trained for individual datasets ?
