### ISSUE TITLE
answer spans for question generation training data

### ISSUE THREAD

**Issue by felicitywang** [microsoft/unilm#68]
Hi,
Could you share how you got the answer spans for training? Are they extracted directly from SQuAD? And there seem to be more lines in your training data than in Du's split, where do those extra data come from?

![image](https://user-images.githubusercontent.com/10904994/75305941-666cc180-57fc-11ea-8c08-d20c98dfa764.png)

Many thanks.

**Comment by WenhuiWang0824** [comment]
Hi,

For each question-passage-answer triples in SQuAD, the passage and answer are used as input to generate its corresponding question. Since the tokenizer used in UniLM is different from [Du et al. (2017)](https://arxiv.org/pdf/1705.00106.pdf), we regenerate the processed data using their [raw json files](https://github.com/xinyadu/nqg/tree/master/data/raw), which contains 75722 examples in the training file.

**Comment by felicitywang** [comment]
Thanks! Closing.
