### ISSUE TITLE
Hardcoded num_classes in VLGeneralizedRCNN implementation

### ISSUE THREAD

**Issue by lvaleriu** [microsoft/unilm#699]
Is there a reason why num_classes value is hardcoded to 5, instead of using self.cfg.MODEL.ROI_HEADS.NUM_CLASSES, as it appears in the comment line?

https://github.com/microsoft/unilm/blob/f6e1cc904ce342066f152f1cfd74005008dbeaa1/layoutlmv3/examples/object_detection/ditod/rcnn_vl.py#L168

**Comment by HYPJUDY** [comment]
Since the `self.cfg` is not set in the `__init__` function of `class VLGeneralizedRCNN(GeneralizedRCNN)`, I use hard-coded numbers in my preliminary experiments for convenience. In fact, the function `_merge_detections` which contains the line you mentioned is not used in the release code. I will delete this function in the next commit. Sorry for the confusion and thanks for reminding!

**Comment by lvaleriu** [comment]
Thank you for your clarification!
