### ISSUE TITLE
How to do inference in downstream task ER s3prl wavlm

### ISSUE THREAD

**Issue by sciai-ai** [microsoft/unilm#704]
I have trained a downstream ER using wavlm in s3prl task where a checkpoint has been saved `dev-best.ckp.`.  Can you please share the inference code that can be used to check the emotion for a given wav file.

I know there is this code to test but this assumes the data to be in the format for IEMOCAP rather than simply a wav file
`data="your IEMOCAP root"

python3 run_downstream.py -m evaluate -t test
-e checkpoint_fold1.ckpt
-o args.expdir=tgt_dir/er/fold1,,config.downstream_expert.datarc.root=$data`

Can we use the saved checkpoint to something along the lines of the code below from HF.

I would want the model to be loaded once quit reloading it every time there is a new wav file input

![image](https://user-images.githubusercontent.com/52277510/166095160-97c41a1c-7779-412e-b2dc-a870ab4f4ff2.png)
{

**Comment by Sanyuan-Chen** [comment]
Hi, we evaluated the WavLM model on ER task following the s3prl repo, and didn't conduct the inference with a given wav file. 
I guess you can modify the IEMOCAPDataset to consume the input wave file. However, this issue is more relevant to s3prl codes, and you may obtain the solution to this issue in s3prl repo.

**Comment by raniataoufik** [comment]
were u able to find the inference code?
