### ISSUE TITLE
Layoutlmv3 import 'auto_class_factory' error

### ISSUE THREAD

**Issue by Intsigstephon** [microsoft/unilm#705]
**Describe the bug**
Model I am using LayoutLMv3:

The problem arises when using:
* [x] my own modified scripts: (give details below)
```
python -m torch.distributed.launch \
  --nproc_per_node=1 --master_port 4398 examples/run_funsd_cord.py \
  --dataset_name funsd \
  --do_eval \
  --model_name_or_path pretrain/layoutlmv3-base-finetuned-funsd \
  --output_dir output/layoutlmv3-base-finetuned-funsd \
  --segment_level_layout 1 \
  --visual_embed 1 \
  --input_size 224 \
  --dataloader_num_workers 4
```

Error Message: 
```
Traceback (most recent call last):
  File "examples/run_funsd_cord.py", line 14, in <module>
    from layoutlmft.data import DataCollatorForKeyValueExtraction
  File "/workspace/repos/unilm/layoutlmft/layoutlmft/__init__.py", line 5, in <module>
    from transformers.models.auto.modeling_auto import auto_class_factory
ImportError: cannot import name 'auto_class_factory' from 'transformers.models.auto.modeling_auto' (/usr/local/lib/python3.7/site-packages/transformers/models/auto/modeling_auto.py)
```

**To Reproduce**
Just run the command above

**Expected behavior**
Ans:  I expected  the above code can run normally  with the environment below.

- Platform:
- Python version:  python3.7
- PyTorch version (GPU?):   
   torch:   '1.7.1+cu101' 
   torchvision:  '0.8.2+cu101'
   CUDA:  10.1

**Comment by HYPJUDY** [comment]
Perhaps this error is caused by a mismatch between the environment and the code. For example, the code is tested on `torch==1.10.0+cu111 torchvision==0.11.1+cu111` and [`transformers==4.12.5`](https://github.com/microsoft/unilm/blob/925de7a9ea500e992ec5de02ea193a5eb9d5aa26/layoutlmv3/requirements.txt#L2)
Please try to prepare the environment according to [README](https://github.com/microsoft/unilm/blob/master/layoutlmv3/README.md#installation) and [requirements](https://github.com/microsoft/unilm/blob/master/layoutlmv3/requirements.txt). 
You can also find suggestions from https://github.com/huggingface/transformers/issues/13591 and https://github.com/microsoft/unilm/issues/438.
