### ISSUE TITLE
How to create label for WPA pretrain task in LayoutLMv3

### ISSUE THREAD

**Issue by 24-solar-terms** [microsoft/unilm#785]
Hello authors! Thank you for sharing your great work!
I am trying to reproduce the pretrain code of LayoutLMv3.
I am wondering how to create label for WPA (Word-Patch Alignment) pretrain task. 
Since most OCR parser can only produce line or segment level result especially in Chinese, how do I know which text token belongs to which image patch accurately?
So far, my idea is just using the length of segment bbox divided by the number of characters in it to get the average position roughly. Could anyone give me some ideas?
Thanks in advance.

**Comment by HYPJUDY** [comment]
A segment-level text bounding box may correspond to several sub-regions of different image patches. I create labels by calculating the percentage of area overlap between two groups of regions.
The WPA is described in the paper as follows.
> The WPA objective is to predict whether a text token's corresponding image tokens are masked. Specifically, we assign an aligned label to an unmasked text token when its corresponding image tokens are also unmasked. Otherwise, we assign an unaligned label.

Here is a more detailed description.
When an unmasked language word's corresponding region is also unmasked, they are aligned. Otherwise, a language word is unaligned with its corresponding region when **more than 98% area** of the region's segment-level bounding box corresponds to masked image patches in the MIM task.

The methods for creating WPA labels are not restricted. Other methods may also works as long as the constructed labels can mine the text and image alignment information.

**Comment by 24-solar-terms** [comment]
OK, thank you very much!
