### ISSUE TITLE
[LayoutReader] What's the difference between max_tgt_length and max_seq_length

### ISSUE THREAD

**Issue by Mountchicken** [microsoft/unilm#795]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...): `LayoutReader`

Hi, thanks for your great work

Could you please share some insights on the difference between `max_source_seq_length`  and  `max_target_seq_length` in `run_seq2seq.py`, and difference between `max_seq_length` and `max_tgt_length` in `decode_seq2seq.py'

**Comment by zlwang-cs** [comment]
The implementation of LayoutReader inherits from the s2s-ft project which you can also find in this repo. Since the training part and decoding part are two separate phases of the process, they are using some different variables for similar usages. The source length refers to the length of the input sequence and the target length refers to the length of the generated sequence. The max_seq_length is the sum of the input and generated sequence length, which means it is the total length that the transformer can handle.

**Comment by Mountchicken** [comment]
@zlwang-cs 
Tks for the reply
