### ISSUE TITLE
Does better/longer pretraining explain most of LayoutLMv3 results? 

### ISSUE THREAD

**Issue by alexmt-scale** [microsoft/unilm#818]
Hello, 

I was reading the LayoutLMv3 paper and noticed on table 3  that the scores that LayoutLMv3 gets without using images are already much higher than LayoutLMv2 (e.g. for FUNSD: 88.64 for LayoutLMv3 vs 82.76 for LayoutLMv2)
I was wondering if this is due to better/longer pretraining or if there's something else that I missed?
It seems that two big components are longer pretraining and using line-level locations versus word-level locations.

Thanks in advance for your response!

**Comment by HYPJUDY** [comment]
Hi. the results in Table 3 of LayoutLMv3 are not directly comparable to those in LayoutLMv2 because the results in Table 3 of LayoutLMv3 were produced by an ablation study with different data sizes and training parameters from the full model. However, I think that the ablated models of LayoutLMv3 generally achieved better results than some previous models in some tasks. This may be due to the training strategy or line-level embedding. We focus on validating the effectiveness of our proposed components with ablation studies and have demonstrated that LayoutLMv3 can achieve better performance with fewer parameters in a simpler way.
