### ISSUE TITLE
Results of Question Generation on SQuAD

### ISSUE THREAD

**Issue by deepaknlp** [microsoft/unilm#9]
Thank you for making the code open-sourced.

It seems that there is an issue with the question generation evaluation script. The evaluation script is producing the near same results as reported in the paper. The evaluation script contains some post-processing methods which is the main source of improvement. 

The majority of the authors have used the [nlg-eval](https://github.com/Maluuba/nlg-eval) to report the performance. With nlg-eval the scores on the test dataset with the released generation output and gold question (test.q.tok.txt)  are as follows:
Bleu_1: 0.407580
Bleu_2: 0.275720
Bleu_3: 0.201373
**Bleu_4: 0.151140**
METEOR: 0.161781
ROUGE_L: 0.436765
I am requesting you to please clarify the difference.

**Comment by WenhuiWang0824** [comment]
We directly use the same evaluation scripts of [Du et al., (2017)]( https://github.com/xinyadu/nqg/tree/master/qgevalcap) to make the comparisons fair. We suggest you also follow the same evaluation scripts so that the results could be compared to other research works.

We only conducted the necessary post-processing to detokenize the subword units into words. In our model, texts are tokenized to subword units by WordPiece (Wu et al., 2016). For instance, the word "forecasted" is split to "forecast" and "##ed", where "##" indicates the pieces belong to one word. So when we do the evaluation, we need to first conduct detokenization. In the script `qg/eval_on_unilm_tokenized_ref.py`, we merge the pieces of each word (for instance, "forecast" and "##ed" are merged to "forecasted"). 

Notice that we merge the pieces of each word in the released output to make the generated questions readable, and we do not merge the pieces in the gold tokenized question file (test.q.tok.txt). If you would like to use your own evaluation package (such as nlg-eval), the detokenization step is **required**. You could use the `detokenize` function in `qg/eval_on_unilm_tokenized_ref.py` to conduct detokenization. Otherwise, there would be a mismatch between the tokenization, which results in incorrect evaluation results. 

In addition, if you did not follow the evaluation scripts as in Du et al., (2017), the results might be slightly different as Du et al., (2017) consider multiple references (if any). 

You could provide us with your evaluation command in case you are still confused.

**Comment by deepaknlp** [comment]
Thanks for the details clarification.
However, if I use the gold test question (`nqg_processed_data/tgt-test.txt) `provided by  Du et al., (2017) and your released test set (`qg.test.output.txt`) then there will no need to detokenize them. 

The results using the [Du et al. (2017)](https://github.com/xinyadu/nqg/blob/master/qgevalcap/eval.py) script are as follows:

```
python2 eval-nqg.py --out_file ../../qg.test.output.txt --src_file ../../nqg_processed_data/src-test.txt --tgt_file ../../nqg_processed_data/tgt-test.txt 
scores: 

Bleu_1: 0.42213
Bleu_2: 0.26280
Bleu_3: 0.17740
Bleu_4: 0.12514
METEOR: 0.26111
ROUGE_L: 0.38709
```
The same with nlg-eval are as follows:
```
nlg-eval --references nqg_processed_data/tgt-test.txt --hypothesis qg.test.output.txt 
Bleu_1: 0.368868
Bleu_2: 0.222525
Bleu_3: 0.148107
Bleu_4: 0.103617
METEOR: 0.246009
ROUGE_L: 0.362789
CIDEr: 0.948406
```
Kindly clarify this.

**Comment by donglixp** [comment]
Hi @deepaknlp ,

I think the reason is that our model is a **cased** model, so the file `qg.test.output.txt` is also cased. However, the file `nqg_processed_data/tgt-test.txt` provided by Du et al., (2017) is **uncased**. If you directly feed them into the evaluation script, there would be many case mismatches. Could you try to convert `qg.test.output.txt` into lower-case and then run the evaluation script?

**Comment by deepaknlp** [comment]
Thank you @donglixp for helping me out. I got improved results by lower-casing the prediction file.

**Comment by donglixp** [comment]
Great to know that your issue has been solved.
